"AWS": Amazon Web Services
"Amazon Web Services (AWS)": Amazon Web Services
"DeepMind": Google DeepMind
"Facebook AI Research": Meta AI
"Meta AI Research": Meta AI
"Azure": Microsoft
"Microsoft Azure": Microsoft
"The Boring Company / SpaceX": SpaceX